import datetime
import os
import sys
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "plugin", "scripts"))
import bring_core as B  # noqa: E402

TODAY = datetime.date(2026, 10, 2)
GEN = "2026-10-02T06:00:00Z"
GEN_TEXT = f"---\nweekly_send_cap: 5\ngenerated_utc: {GEN}\n---\n\n## Multi\nid: PIP-64\nkind: send\n\n## Other\nid: PIP-1\n"
HAND_TEXT = "## Multi\nid: PIP-64\nkind: send\n\n## Other\nid: PIP-1\n"


def ids(text, entries):
    cfg, acts = B.parse_actions(text)
    return [a["id"] for a in B.open_actions(acts, entries, TODAY, cfg)]


def e(kind, utc, id_="PIP-64"):
    return {"kind": kind, "id": id_, "utc": utc, "date": utc[:10]}


class OpenActionsTests(unittest.TestCase):
    def test_multistep_sent_then_regenerated_resurfaces(self):
        self.assertEqual(ids(GEN_TEXT, [e("sent", "2026-09-25T10:00:00Z")]), ["PIP-64", "PIP-1"])

    def test_same_day_log_after_generation_hides(self):
        self.assertEqual(ids(GEN_TEXT, [e("sent", "2026-10-02T09:00:00Z")]), ["PIP-1"])
        self.assertEqual(ids(GEN_TEXT, [e("decided", "2026-10-02T09:00:00Z")]), ["PIP-1"])

    def test_closed_and_shipped_hide_permanently(self):
        for k in ("closed", "shipped"):
            self.assertEqual(ids(GEN_TEXT, [e(k, "2026-07-01T10:00:00Z")]), ["PIP-1"])

    def test_hand_written_keeps_old_rule(self):
        self.assertEqual(ids(HAND_TEXT, [e("sent", "2026-09-25T10:00:00Z")]), ["PIP-1"])

    def test_same_day_skip_hides_only_today(self):
        self.assertEqual(ids(GEN_TEXT, [e("skipped", "2026-10-02T09:00:00Z")]), ["PIP-1"])
        self.assertEqual(ids(GEN_TEXT, [e("skipped", "2026-10-01T09:00:00Z")]), ["PIP-64", "PIP-1"])

    def test_generated_marker_without_stamp_uses_header(self):
        cfg, _ = B.parse_actions("<!-- GENERATED by x -->\n## A\nid: A\n")
        self.assertTrue(cfg["generated"])
        self.assertIsNone(cfg["generated_utc"])


if __name__ == "__main__":
    unittest.main()
